### PR TITLE
Various minor improvements

### PR DESCRIPTION
**Pull request by alexmojaki**

### CODE REVIEW

**Comment by cool-RR** [comment]
Great, except 2 things:

1. When you added `u` to a multiline string, add it to all its parts.
2. I disagree with moving down `if len(lines) != len(expected_entries):` etc.

Also, you found a bug! And inspired a feature request: #58

**Comment by alexmojaki** [comment]
1. Actually, all that syntax is getting to me. What do you think of:

```python
def test_unavailable_source():
    with temp_file_tools.create_temp_folder(prefix='pysnooper') as folder, \
            sys_tools.TempSysPathAdder(str(folder)):
        module_name = 'iaerojajsijf'
        python_file_path = folder / ('%s.py' % (module_name,))
        content = u'''
import pysnooper
@pysnooper.snoop()
def f(x):
    return x
'''
        with python_file_path.open('w') as python_file:
            python_file.write(content)
```

or

```python
unavailable_source_content = u'''
import pysnooper
@pysnooper.snoop()
def f(x):
    return x
'''


def test_unavailable_source():
    with temp_file_tools.create_temp_folder(prefix='pysnooper') as folder, \
            sys_tools.TempSysPathAdder(str(folder)):
        module_name = 'iaerojajsijf'
        python_file_path = folder / ('%s.py' % (module_name,))
        with python_file_path.open('w') as python_file:
            python_file.write(unavailable_source_content)
```

or

```python
from textwrap import dedent

def test_unavailable_source():
    with temp_file_tools.create_temp_folder(prefix='pysnooper') as folder, \
            sys_tools.TempSysPathAdder(str(folder)):
        module_name = 'iaerojajsijf'
        python_file_path = folder / ('%s.py' % (module_name,))
        content = dedent(u'''
            import pysnooper
            @pysnooper.snoop()
            def f(x):
                return x
        ''')
        with python_file_path.open('w') as python_file:
            python_file.write(content)
```

**Comment by alexmojaki** [comment]
2. It's important to have more information than just a differing length. I've made the output much clearer now. Here's a sample failure:

```
E           Starting var:.. foo = 'baba'                               VariableEntry(name='foo', prefix='', value_regex=re.compile("u?'baba'"))  
E           08:30:05.702801 call        21     def my_function(foo):   <tests.utils.CallEntry object at 0x110326e48>  
E           08:30:05.703858 line        22         x = 7               <tests.utils.LineEntry object at 0x110326d68>  
E           New var:....... x = 7                                      VariableEntry(name='x', value='7', prefix='')  
E           08:30:05.703911 line        23         y = 8               <tests.utils.LineEntry object at 0x110326ef0>  
E           New var:....... y = 8                                      <tests.utils.LineEntry object at 0x110326f60>  <===
E           08:30:05.703951 line        24         return y + x        VariableEntry(name='y', value='8', prefix='')  <===
E           08:30:05.704064 return      24         return y + x        <tests.utils.LineEntry object at 0x110326c18>  <===
E           Return value:.. 15                                         <tests.utils.ReturnEntry object at 0x110326fd0>  <===
E                                                                      ReturnValueEntry(value='15', prefix='')  <===
E           Output has 9 lines, while we expect 10 lines.
```

**Comment by cool-RR** [comment]
Third option, except call it as textwrap.dedent.

**Comment by cool-RR** [comment]
Great work Alex!

**Pull request merged**
