### PR TITLE
variables 파일 주석 추가

### PR DESCRIPTION
**Pull request by xhdzl6280**

### CODE REVIEW

**Comment by xhdzl6280** [comment]
close this commit

**Comment by cool-RR** [comment]
Hi @xhdzl6280 . Why are you opening pull requests and closing them? Also, note that we communicate in English here.

**Comment by xhdzl6280** [comment]
I'm sorry to open this pull request at this repository. I intended to open this pull request in my team repository, but I'm not familiar with github yet so I did a mistake..

**Comment by xhdzl6280** [comment]
When I opened this pull request, I was too embarrassed to take other actions, so I just closed this request without any other mentions. However, now I know that I behaved disrespectfully and you may feel uncomfortable. I want to apologize to you about my actions and this late apology. I feel really sorry about this.

**Comment by cool-RR** [comment]
It's okay, it's all good.

**Pull request closed without merging**
