### PR TITLE
[WIP] Include filenames when depth >= 2

### PR DESCRIPTION
**Pull request by codexetreme**
I have added some lines of code that are supposed to implement this feature

### CODE REVIEW

**Comment by codexetreme** [comment]
So, the main issue I face is, it is printing the file name for the first file, and not for any more subsequent files or for function calls

test_pysnooper_depth.py

```
import os
from ys import prep

import pysnooper
@pysnooper.snoop(depth=2)
def print_dir(path):
	print (os.listdir(path)[:3])
	wassup()
	prep()


def wassup():
	print ('hello')

print_dir('/home/codexetreme/Documents/')
```


ys.py

```
def prep():
    print ('yay')
```

**Comment by codexetreme** [comment]
Working on: #6

cc: @cool-RR

**Comment by alexmojaki** [comment]
Look at the context where you've added the code. It's only for calls to decorated functions.

**Comment by cool-RR** [comment]
@codexetreme See Alex's comments.

**Comment by codexetreme** [comment]
Ok, I have fixed the issue, for the most part, my question now is, should I make changes to the tests (I have created one for testing this) as they seem to be failing since there is an unaccounted line in the output log (the line that shows the file name if depth >=2)

**Comment by cool-RR** [comment]
The tests should be modified to pass, yes. And your entire business logic should start with `if self.depth >= 2` because most users aren't going to use that.

**Comment by cool-RR** [comment]
Closed because of low activity.

**Pull request closed without merging**
