### PR TITLE
Print line containing actual function name for "call" event

### PR DESCRIPTION
**Pull request by czietz**
Implements https://github.com/cool-RR/PySnooper/issues/28, including tests.

### CODE REVIEW

**Comment by cool-RR** [comment]
That's nice, but I'm a little worried about line_no going forward like that. I suggest that you do a search for a line that matches the expression `"^ +def" after any number of lines that start with "@". If you don't find such a line, it's possible we're dealing with a case we don't understand, so cancel your transformation and show the original line with the decorator, just to play it safe.

If you can also add a test for that safe behavior, that'll be extra cool, but that's optional.

**Comment by czietz** [comment]
I added a check that the line that is found actually starts with `def` (after possible white-space, of course). 

After looking at the grammar for a Python function definition (https://docs.python.org/3/reference/compound_stmts.html#function-definitions), I fail to come up with _any_ test-case that could trigger this. If you have an idea, I'll be happy to implement the test.

**Comment by czietz** [comment]
I fixed items 1-4. 

I have no idea how to write a test for 3, though. I tested that it works as intended by locally modifying the source to search for `xef` instead of `def`, in which case it will correctly revert to the original line, i.e., the decorator. But that's nothing that can be added to a test-case.

If you insist on a test-case for 3, then please consider this pull-request retracted.

**Comment by cool-RR** [comment]
Great work @czietz ! I merged your commits, did some refactoring on them and added a test for lambda. (I merged them directly into the repo, not through the pull request, so I had to close it.)

**Pull request closed without merging**
