### PR TITLE
setup.py: add test dependencies via "extras"

### PR DESCRIPTION
**Pull request by pohmelie**

### CODE REVIEW

**Comment by cool-RR** [comment]
@bittner This looks good to me, unless you disapprove.

**Comment by bittner** [comment]
Technically, this looks fine.

@pohmelie Can you describe your use case?

**Comment by cool-RR** [comment]
(Peter, feel free to hit the merge button when you're satisfied it's good.)

**Comment by pohmelie** [comment]
@bittner
`pip install -e ./PySnooper[tests]` to be ready for development (aka run tests). Also it is good for CI to easily be ready to run tests.

**Comment by bittner** [comment]
Can you document your use case in the README? I think the [Contribute](https://github.com/cool-RR/PySnooper#contribute) section would be a good place. Thank you!

**Comment by julius210** [comment]
Love to invest in bitcoin this is ur chance

**Comment by bittner** [comment]
@pohmelie Your change to the README seems fine. Can you combine this with the original commit (i.e. squash the two commits)? Thank you!

**Comment by bittner** [comment]
... and, if you care, you may want to update your name in the [AUTHORS](https://github.com/cool-RR/PySnooper/blob/master/AUTHORS#L12) file. :smirk:

**Comment by pohmelie** [comment]
@bittner 
> Can you combine this with the original commit (i.e. squash the two commits)?

There is a squash on merge optoin just inside github, no need to force push squashed commits for contributor.
> you may want to update your name

This name is just fine :smile:

**Pull request merged**
