### PR TITLE
Add classes to automatically track attributes, keys, etc. of variables

### LINKED ISSUE #59: Feature request: Add `exploding_variables` argument
Any exploding variable will not only be tracked, but all its attributes will be tracked too.

### PR DESCRIPTION
**Pull request by alexmojaki**
Closes #59 

Sample usage:

```python
from types import SimpleNamespace

import pysnooper
from pysnooper.variables import Attrs, Indices, Keys, Enumerate


@pysnooper.snoop(variables=(
        Keys('d', exclude='c'),
        Attrs('point'),
        Indices('lst')[-3:],
        Enumerate('s'),
))
def foo():
    d = {'a': 1, 'b': 2, 'c': 'ignore'}
    point = SimpleNamespace(x=3, y=4)
    lst = list(range(1000))
    s = {7, 8, 9}


foo()
```

Output:

```
19:01:11.689207 call        13 def foo():
19:01:11.779673 line        14     d = {'a': 1, 'b': 2, 'c': 'ignore'}
New var:....... (d)['a'] = 1
New var:....... (d)['b'] = 2
New var:....... d = {'a': 1, 'b': 2, 'c': 'ignore'}
19:01:11.872593 line        15     point = SimpleNamespace(x=3, y=4)
New var:....... (point).x = 3
New var:....... (point).y = 4
New var:....... point = namespace(x=3, y=4)
19:01:12.000584 line        16     lst = list(range(1000))
New var:....... (lst)[997] = 997
New var:....... (lst)[998] = 998
New var:....... (lst)[999] = 999
New var:....... lst = [0, 1, 2, 3, 4, 5, ...]
19:01:12.128228 line        17     s = {7, 8, 9}
New var:....... (s)<0> = 8
New var:....... (s)<1> = 9
New var:....... (s)<2> = 7
New var:....... s = {7, 8, 9}
19:01:12.260525 return      17     s = {7, 8, 9}
Return value:.. None
```

### CODE REVIEW

**Comment by cool-RR** [comment]
How is this better than `variables=d.keys()`?

**Comment by alexmojaki** [comment]
This shows values, not just keys, so I'm assuming you mean `d.items()`, which really is just as good as `d`. This ensures that all items and their changes are shown and nicely formatted. Otherwise you get the problem in #73, and even when modifications are reported, the user has to manually search through entries to find the differences.

**Comment by cool-RR** [comment]
Ah, I understand. 

I don't like all these classes that people will need to know. I'm sorry, I'm afraid of adding more complexity to the project for features that I don't know whether people will find useful.

**Comment by alexmojaki** [comment]
Also `reprlib` doesn't have good reprs for mappings other than raw `dict`s, so for example in this case:

```python
from collections import OrderedDict

import pysnooper
from pysnooper.variables import Keys

@pysnooper.snoop(variables=(
        Keys('d'),
))
def foo():
    d = OrderedDict()
    d[1] = list(range(20))
    d[2] = list(range(40))

foo()
```

```
20:57:49.925572 call        11 def foo():
20:57:49.925890 line        12     d = OrderedDict()
New var:....... d = OrderedDict()
20:57:49.926047 line        13     d[1] = list(range(20))
New var:....... (d)[1] = [0, 1, 2, 3, 4, 5, ...]
Modified var:.. d = OrderedDict([(1, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])])
20:57:49.926290 line        14     d[2] = list(range(40))
New var:....... (d)[2] = [0, 1, 2, 3, 4, 5, ...]
Modified var:.. d = OrderedDict([(1, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, ...8, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])])
20:57:49.926611 return      14     d[2] = list(range(40))
Return value:.. None
```

you can really only see what happened in the `(d)[2] =` line, not the `Modified var:.. d = ` line.

**Comment by alexmojaki** [comment]
OK, I added automatic dispatching. It could alternatively use the Mapping and Sequence ABCs, each method has pros and cons. Then I'd suggest documenting the classes under an 'Advanced usage' section for people interested in greater control (making sure the right class is used, excluding keys, slicing indices, and maybe other functions in the future such as depth).

**Comment by alexmojaki** [comment]
I decided to go with the collections ABCs since that's less likely to trigger unwanted behaviour.

Here's a sample of the automatic API:

```python
from types import SimpleNamespace

import pysnooper


@pysnooper.snoop(exploded_variables='d point lst'.split())
def foo():
    d = {'a': 1, 'b': 2, 'c': 'ignore'}
    point = SimpleNamespace(x=3, y=4)
    lst = list(range(5))


foo()
```

```
09:11:50.682783 call         7 def foo():
09:11:50.683004 line         8     d = {'a': 1, 'b': 2, 'c': 'ignore'}
New var:....... (d)['a'] = 1
New var:....... (d)['b'] = 2
New var:....... (d)['c'] = 'ignore'
New var:....... d = {'a': 1, 'b': 2, 'c': 'ignore'}
09:11:50.683432 line         9     point = SimpleNamespace(x=3, y=4)
New var:....... (point).x = 3
New var:....... (point).y = 4
New var:....... point = namespace(x=3, y=4)
09:11:50.683996 line        10     lst = list(range(5))
New var:....... (lst)[0] = 0
New var:....... (lst)[1] = 1
New var:....... (lst)[2] = 2
New var:....... (lst)[3] = 3
New var:....... (lst)[4] = 4
New var:....... lst = [0, 1, 2, 3, 4]
09:11:50.684502 return      10     lst = list(range(5))
Return value:.. None
```

**Comment by cool-RR** [comment]
Could you rebase or resolve conflicts before I review?

**Comment by cool-RR** [comment]
Looks like there are still conflicts to resolve, do you need help with that?

**Comment by alexmojaki** [comment]
I'm not seeing any conflicts.

**Comment by cool-RR** [comment]
See this screenshot: https://www.dropbox.com/s/nd6pthuhr5ubol5/screenshot_HOPPER_2019-04-30_172302.jpg?dl=0

If you'll want help with the conflicts, let me know.

**Comment by cool-RR** [comment]
See this screenshot: https://www.dropbox.com/s/nd6pthuhr5ubol5/screenshot_HOPPER_2019-04-30_172302.jpg?dl=0

If you'll want help with the conflicts, let me know.

**Comment by alexmojaki** [comment]
screen

**Comment by alexmojaki** [comment]
Send me the link to command line instructions and I'll take a look later.

**Comment by cool-RR** [comment]
@alexmojaki Can you please add me as a collaborator here? https://github.com/alexmojaki/PySnooper/

**Comment by cool-RR** [comment]
Sorry for the delay here. Looking good. I rebased and touched up a few places, the result is in the `development` branch. After you give me permission to your repo, I'll push it into this PR.

Here are more things needed to merge:

1. Tests
2. Update the docstring and the readme (or advanced usage, that's good too.)
4. Protect from infinite sequence, and test.
5. Use `ABC`, `@abstractmethod` and such on the classes in variables
6. `_safe_keys` should be a top-level function since it doesn't use `self`
7. No need for `()` in `raise NotImplementedError()`
8. I think you can use vars instead of __dict__ and __slots_. 

I'm willing to split a few items with you if you'd like. You should do at least the first two though, because problems with your design might come up. Let me know which of the items you'd like me to do.

**Comment by alexmojaki** [comment]
3. I'm not iterating blindly anywhere any more as I removed `Enumerate`. `Indices` uses `len` so nothing infinite can happen.
4. The only candidate for `@abstractmethod` is `BaseVariable._items`. Adding it would probably waste reader's time as they think about why it hasn't been used on other methods.
5. `_safe_keys` uses `self`.
7. `vars` simply returns `__dict__`. There was a discussion to make it account for `__slots__` but it was rejected, which disappointed me.

**Comment by cool-RR** [comment]
I agree on 3 and 5.

Regarding 4: I think that `@abstractmethod` is fitting for `_items`.

Regarding 7: Okay, but there should be a test that this logic doesn't fail for a few objects that don't have `__dict__`.

**Comment by cool-RR** [comment]
Looking good. As far as I'm concerned, this only needs the "advanced usage" text file, with a link from the readme, and it's good to merge. Let me know if you'll want help on that.

**Comment by alexmojaki** [comment]
I think we should probably go for a shorter parameter name, like `explode` or `expand`.

**Comment by cool-RR** [comment]
I do think that the argument name is too long, and `explode` would be cool, the problem is that it sounds too much like a boolean and I don't want people to try to pass `True` in. By the way, can you rename from `exploded_variables` to `exploding_variables`? I think the latter sounds cooler.

**Comment by alexmojaki** [comment]
I can attest that it's hard to remember if it's `exploded_variables` or `exploding_variables`. You wrote `exploding` in the issue, but I wrote `exploded` in the code, and then screwed up again and wrote `exploding` in the docs.

**Comment by cool-RR** [comment]
(If you'd like me to do the renaming, I will.)

**Comment by cool-RR** [comment]
Actually, I'll just do it now.

**Comment by alexmojaki** [comment]
It also has nothing to do with variables specifically. It's for arbitrary expressions.

**Comment by alexmojaki** [comment]
On that note, the name `variables` doesn't make sense either, because all variables are tracked, it only makes sense to pass a more complicated expression.

**Comment by cool-RR** [comment]
> On that note, the name `variables` doesn't make sense either, because all variables are tracked, it only makes sense to pass a more complicated expression. I think `watch` would be better to fit with traditional debugger terminology. Maybe `expressions`.

Agreed.

**Comment by alexmojaki** [comment]
Awesome!

What do you think of just `exploding`? Shorter, doesn't sound like a boolean. Bit weird though.

**Comment by cool-RR** [comment]
Sorry, I've grown to really like `watch_explode` :)

**Comment by alexmojaki** [comment]
Oh, I didn't see that one. Commits are moving too fast. That's pretty good.

**Comment by cool-RR** [comment]
Whew, this PR exploded :) Great work Alex, this is a very nice addition to our functionality.

**Pull request merged**
