### PR TITLE
Python 3.10 compatibility

### PR DESCRIPTION
**Pull request by frenzymadness**
Fixes: #218 

This is the minimum I had to implement to make the tests compatible with Python 3.10. I also did some improvements in configs for CI and tests.

I'm not sure what is your approach to flake8 and pylint because there are already many errors and it's hard to find the ones possible caused by me here. Also, it's kinda verbose to use the names for keyword arguments instead of `**kwargs` for the optional ones but I've followed the current codebase.

All unit tests are passing locally so we'll see what CI thinks about it.

### CODE REVIEW

**Comment by cool-RR** [comment]
This looks good to me. @alexmojaki Do you want to take a look? 

A few notes:
1. Anywhere you use `(3,10)`, space it out: `(3, 10)`
2. I don't like that the `expected_entries` variable gets replaced. Can you remove the assignment `expected_entries = filtered_expected_entries` and just iterate over `filtered_expected_entries` in the `for` loop?
3. The CI is failing for some reason, but I guess you noticed that.

**Comment by frenzymadness** [comment]
Thanks for the feedback. I've tried to improve the logic to be more readable. See the latest fixup commit.

The CI fails because Travis has not the latest Python 3.10 beta 1 yet, it's still on alpha 5. If you want to, I can add the 3.10 job into `allow_failures` and we can remove it from there once Travis updates its Python.

**Comment by cool-RR** [comment]
Great job. Yes, using `allow_failures` sounds good to me.

**Comment by alexmojaki** [comment]
No comments from me because I don't like the 'Entry' style tests anyway.

**Comment by cool-RR** [comment]
Hmm, any idea why Travis still fails?

**Comment by frenzymadness** [comment]
The configuration is kinda different when handled by the tox-travis, let me find the right way.

**Comment by cool-RR** [comment]
Okay, Travis is green. Are we good to merge? (After the merge I'll do a version bump and make a release.)

**Comment by frenzymadness** [comment]
I think we are. Thank you!

**Comment by cool-RR** [comment]
Done and release. Thank you.

**Comment by cool-RR** [comment]
Right, done.

**Pull request merged**
