### PR TITLE
Compatibility with jupyter_core version 5+

### PR DESCRIPTION
**Pull request by sizhky**
Specifically improves compatibility with jupyter environments that use ipykernels like jupyter-lab

https://github.com/cool-RR/PySnooper/issues/230

### CODE REVIEW

**Comment by cool-RR** [comment]
Looks good. 

1. I think that the `if` after your code should be an `elif`.
2. Can you show a screenshot of before and after this change in the Jupyter shell?
3. Are you reasonable sure you're not breaking anything else? 
4. If there happens to be a Windows version of `/var/folders/`, it'll be nice to include it too. Not a dealbreaker.
5. Change `\d` in the regular expression to `[0-9]`.

**Comment by sizhky** [comment]
- [x] I think that the if after your code should be an elif.
- [x] Can you show a screenshot of before and after this change in the Jupyter shell?
- [x] Are you reasonable sure you're not breaking anything else?
- [ ] If there happens to be a Windows version of /var/folders/, it'll be nice to include it too. Not a dealbreaker.
I'm not in a position to test this.
- [x] Change \d in the regular expression to [0-9].

image

**Comment by cool-RR** [comment]
Good job. All done and ready for merging?

**Comment by sizhky** [comment]
Yep!

**Comment by sizhky** [comment]
Anything still pending?

**Comment by sizhky** [comment]
yeah it's working

**Comment by cool-RR** [comment]
Thank you. Good job.

**Pull request closed without merging**
